name: Daily Scout Brief

on:
  schedule:
    - cron: '0 14 * * *'  # 8am MT / 2pm UTC daily
  workflow_dispatch:       # manual trigger

jobs:
  scout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run scout
        env:
          NANOGPT_API_KEY: ${{ secrets.NANOGPT_API_KEY }}
          X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
        run: python3 scout.py --save --save-tweets

      - name: Commit brief
        run: |
          git config user.name "scout-bot"
          git config user.email "scout@local"
          git add briefs/
          git diff --cached --quiet || git commit -m "scout: $(date +%Y-%m-%d)"
          git push
